# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(397, 203)
        self.filelabel = QtWidgets.QLabel(Form)
        self.filelabel.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.filelabel.setObjectName("filelabel")
        self.maxlabel = QtWidgets.QLabel(Form)
        self.maxlabel.setGeometry(QtCore.QRect(20, 60, 131, 16))
        self.maxlabel.setObjectName("maxlabel")
        self.minlabel = QtWidgets.QLabel(Form)
        self.minlabel.setGeometry(QtCore.QRect(20, 100, 141, 16))
        self.minlabel.setObjectName("minlabel")
        self.averagelabel = QtWidgets.QLabel(Form)
        self.averagelabel.setGeometry(QtCore.QRect(20, 130, 131, 31))
        self.averagelabel.setObjectName("averagelabel")
        self.fileline = QtWidgets.QLineEdit(Form)
        self.fileline.setGeometry(QtCore.QRect(90, 20, 201, 21))
        self.fileline.setObjectName("fileline")
        self.maxline = QtWidgets.QLineEdit(Form)
        self.maxline.setGeometry(QtCore.QRect(160, 60, 221, 20))
        self.maxline.setObjectName("maxline")
        self.minline = QtWidgets.QLineEdit(Form)
        self.minline.setGeometry(QtCore.QRect(160, 100, 221, 20))
        self.minline.setObjectName("minline")
        self.averageline = QtWidgets.QLineEdit(Form)
        self.averageline.setGeometry(QtCore.QRect(160, 140, 221, 20))
        self.averageline.setObjectName("averageline")
        self.bt = QtWidgets.QPushButton(Form)
        self.bt.setGeometry(QtCore.QRect(300, 20, 81, 23))
        self.bt.setObjectName("bt")
        self.errorlabel = QtWidgets.QLabel(Form)
        self.errorlabel.setGeometry(QtCore.QRect(20, 170, 47, 13))
        self.errorlabel.setObjectName("errorlabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.filelabel.setText(_translate("Form", "Имя файла:"))
        self.maxlabel.setText(_translate("Form", "Максимальное значение:"))
        self.minlabel.setText(_translate("Form", "Минимальное значение:"))
        self.averagelabel.setText(_translate("Form", "Среднее значение:"))
        self.bt.setText(_translate("Form", "Рассчитать"))
        self.errorlabel.setText(_translate("Form", "TextLabel"))
